### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by jaapio**
Some PR to check if we can simulate the issue of invalid key parsing in isolation on this lib.

### CODE REVIEW

**Comment by jaapio** [comment]
@theseer I think this PR shows a part of the issue. The php extension is returning `false` on import failure where this lib is behaving like everything went ok.... which is not the case... Could that trigger the issue in phive? 

What do you think about creating an abstraction for the php extension as well. Which allows us to throw an exception instead of returning `false`

**Comment by theseer** [comment]
I've been pondering about extending this lib into a full blown component, rather than "just" mimicking the pecl gnupg extension's API.

The longer I think about it, the better I start to like the idea. That would also allow us to remove the class_alias call. And we can probably move some of the logic from phive over to here.

Let's make that an explicit issue and discuss there.

**Comment by jaapio** [comment]
Sounds good, not sure if I have time to help, but I'm always open to just help you with some discussion.

**Comment by theseer** [comment]
I'll look into it next week or maybe over the weekend. :) Thanks, I'll ping you.

**Comment by jaapio** [comment]
Hi
is there any progress on this? I have some odd issues again regarding gpg validation in phive. When I was looking at the status phive I came across this issue :-) 

Are you still planning to build something yourself or are you open to a full overhoal of this library? 

This could be a nice start: https://github.com/tommy-muehle/php-gpg-verifier

**Comment by theseer** [comment]
It's still a plan :)

So far though, I didn't have the time to do anything on this.

**Comment by jaapio** [comment]
If we can discuss the approach I would be happy to implement the plan :-). Please let me know how I can help. Or just give me a card blance and I will do a proposal. 

Phive is an awesome tool that should get more attention. It is really helping us with phpDocumentor. So anything I can do to help you improving the stability of phive will contribute indirectly to phpDocumentor.

**Comment by theseer** [comment]
Thanks for the praise :)

If you feel like do have a 1:1 video chat on it the upcoming days? Then we could probably agree on a plan :)

**Comment by jaapio** [comment]
Let's do that :+1:

**Pull request closed without merging**
